package org.absorb.world.biome;

import org.absorb.particle.ParticleBuilder;
import org.absorb.particle.ParticleTypes;
import org.absorb.utils.Identifiable;
import org.absorb.world.biome.properties.BiomePropertiesBuilder;
import org.absorb.world.biome.properties.BiomeWeather;
import org.absorb.world.biome.properties.GrassModifier;
import org.absorb.world.biome.properties.TemperatureModifier;
import org.absorb.world.biome.sound.BiomeSounds;

@SuppressWarnings("unused")
public interface Biomes {

    Biome VOID = new BiomeBuilder()
            .setNetworkId(0)
            .setCategory(BiomeCategory.NONE)
            .setDownfall(0.5f)
            .setTemperature(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setFogColour(12638463)
                    .setWaterColour(4159204)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .setWeather(BiomeWeather.NONE)
                    .build()
            )
            .setHost(Identifiable.MINECRAFT_HOST)
            .setName("the_void")
            .build();

    Biome PLAIN = new BiomeBuilder()
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7907327)
                    .build())
            .setNetworkId(1)
            .setDepth(0.125f)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTemperature(0.800000011920929f)
            .setScale(0.05000000074505806f)
            .setDownfall(0.4000000059604645f)
            .setCategory(BiomeCategory.PLAINS)
            .setTickDelay(6000)
            .setName("plains")
            .setHost(Identifiable.MINECRAFT_HOST)
            .build();

    Biome SUNFLOWER_PLAINS = new BiomeBuilder()
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(2)
            .setName("sunflower_plains")
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7907327)
                    .build())
            .setTickDelay(6000)
            .setOffset(2.0)
            .setTemperature(0.8f)
            .setDownfall(0.4f)
            .setBlockSearchExtent(8)

            .setCategory(BiomeCategory.PLAINS)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .build();

    Biome SNOWY_PLAINS = new BiomeBuilder()
            .setName("snowy_plains")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setCategory(BiomeCategory.ICY)
            .setTemperature(0.0f)
            .setDownfall(0.5f)
            .setNetworkId(3)
            .setBlockSearchExtent(8)
            .setTickDelay(6000)
            .setOffset(2.0)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setSkyColour(8364543)
                    .setWaterFogColour(329011)
                    .setFogColour(12638463)
                    .setWaterColour(4159204)
                    .build())
            .build();

    Biome ICE_SPIKES = new BiomeBuilder()
            .setDownfall(0.5f)
            .setTemperature(0.0f)
            .setCategory(BiomeCategory.ICY)
            .setName("ice_spikes")
            .setNetworkId(4)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8364543)
                    .setWeather(BiomeWeather.SNOW)
                    .build())
            .build();

    Biome DESERT = new BiomeBuilder()
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(5)
            .setName("desert")
            .setCategory(BiomeCategory.DESERT)
            .setDownfall(0.0f)
            .setTemperature(2.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setSkyColour(7254527)
                    .setWaterFogColour(329011)
                    .setFogColour(12638463)
                    .setWaterColour(4159204)
                    .build())
            .build();

    Biome SWAMP = new BiomeBuilder()
            .setTemperature(0.8f)
            .setDownfall(0.9f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.SWAMP)
            .setName("swamp")
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(6)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(6388580)
                    .setFogColour(12638463)
                    .setWaterFogColour(2302743)
                    .setFoliageColour(6975545)
                    .setSkyColour(7907327)
                    .setGrassColourModifier(GrassModifier.SWAMP)
                    .build())
            .build();

    Biome FOREST = new BiomeBuilder()
            .setTemperature(0.7f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.FOREST)
            .setName("forest")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(7)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7972607)
                    .build())
            .build();

    Biome FLOWER_FOREST = new BiomeBuilder()
            .setTemperature(0.7f)
            .setDownfall(0.8f)
            .setCategory(BiomeCategory.FOREST)
            .setName("flower_forest")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(8)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7972607)
                    .build())
            .build();

    Biome BIRCH_FOREST = new BiomeBuilder()
            .setTemperature(0.6f)
            .setDownfall(0.6f)
            .setCategory(BiomeCategory.FOREST)
            .setName("birch_forest")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(9)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8037887)
                    .build())
            .build();

    Biome DARK_FOREST = new BiomeBuilder()
            .setTemperature(0.7f)
            .setDownfall(0.8f)
            .setCategory(BiomeCategory.FOREST)
            .setName("dark_forest")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(10)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7972607)
                    .setGrassColourModifier(GrassModifier.DARK_FOREST)
                    .build())
            .build();
    Biome OLD_GROWTH_BIRCH_FOREST = new BiomeBuilder()
            .setTemperature(0.6f)
            .setDownfall(0.6f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.FOREST)
            .setName("old_growth_birch_forest")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(11)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8037887)
                    .build())
            .build();
    Biome OLD_GROWTH_PINE_TAIGA = new BiomeBuilder()
            .setTemperature(0.3f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.TAIGA)
            .setName("old_growth_pine_taiga")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(12)
            .setBlockSearchExtent(8)

            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8168447)
                    .build())
            .build();
    Biome OLD_GROWTH_SPRUCE_TAIGA = new BiomeBuilder()
            .setTemperature(0.25f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.TAIGA)
            .setName("old_growth_spruce_taiga")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(13)
            .setBlockSearchExtent(8)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233983)
                    .build())
            .build();
    Biome TAIGA = new BiomeBuilder()
            .setTemperature(0.25f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.TAIGA)
            .setName("taiga")
            .setBlockSearchExtent(8)

            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(14)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233983)
                    .build())
            .build();
    Biome SNOWY_TAIGA = new BiomeBuilder()
            .setTemperature(-0.5f)
            .setDownfall(0.4f)
            .setCategory(BiomeCategory.TAIGA)
            .setName("snowy_taiga")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(15)
            .setBlockSearchExtent(8)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4020182)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8625919)
                    .build())
            .build();
    Biome SAVANNA = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setCategory(BiomeCategory.SAVANNA)
            .setName("savanna")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(16)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();
    Biome SAVANNA_PLATEAU = new BiomeBuilder()
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setCategory(BiomeCategory.SAVANNA)
            .setName("savanna_plateau")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(17)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();
    Biome WINDSWEPT_HILLS = new BiomeBuilder()
            .setTemperature(0.2f)
            .setDownfall(0.3f)
            .setCategory(BiomeCategory.EXTREME_HILLS)
            .setName("windswept_hills")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setNetworkId(18)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233727)
                    .build())
            .build();
    Biome WINDSWEPT_GRAVELLY_HILLS = new BiomeBuilder()
            .setTemperature(0.2f)
            .setDownfall(0.3f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.EXTREME_HILLS)
            .setName("windswept_gravelly_hills")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setNetworkId(19)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233727)
                    .build())
            .build();
    Biome WINDSWEPT_FOREST = new BiomeBuilder()
            .setTemperature(0.2f)
            .setDownfall(0.3f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setCategory(BiomeCategory.EXTREME_HILLS)
            .setName("windswept_forest")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(20)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233727)
                    .build())
            .build();

    Biome WINDSWEPT_SAVANNA = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setCategory(BiomeCategory.SAVANNA)
            .setName("windswept_savanna")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setNetworkId(21)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();
    Biome JUNGLE = new BiomeBuilder()
            .setTemperature(0.95f)
            .setDownfall(0.9f)
            .setCategory(BiomeCategory.JUNGLE)
            .setName("jungle")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(22)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7842047)
                    .build())
            .build();
    Biome SPARSE_JUNGLE = new BiomeBuilder()
            .setTemperature(0.95f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setCategory(BiomeCategory.JUNGLE)
            .setName("sparse_jungle")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(23)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7842047)
                    .build())
            .build();
    Biome BAMBOO_JUNGLE = new BiomeBuilder()
            .setTemperature(0.95f)
            .setDownfall(0.9f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setCategory(BiomeCategory.JUNGLE)
            .setName("bamboo_jungle")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(24)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7842047)
                    .build())
            .build();
    Biome BADLANDS = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setCategory(BiomeCategory.MESA)
            .setName("badlands")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(25)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .setGrassColour(9470285)
                    .setFoliageColour(10387789)
                    .build())
            .build();
    Biome ERODED_BANDLANDS = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setCategory(BiomeCategory.MESA)
            .setName("eroded_badlands")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(26)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .setGrassColour(9470285)
                    .setFoliageColour(10387789)
                    .build())
            .build();
    Biome WOODED_BADLANDS = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setCategory(BiomeCategory.MESA)
            .setName("wooded_badlands")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(27)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .setGrassColour(9470285)
                    .setFoliageColour(10387789)
                    .build())
            .build();
    Biome MEADOW = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.8f)
            .setCategory(BiomeCategory.MOUNTAIN)
            .setName("meadow")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(28)
            .setBlockSearchExtent(8)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setMusicSound(BiomeSounds.OVERWORLD_MEADOW)
            .setReplaceCurrentMusic(false)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(937679)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome GROVE = new BiomeBuilder()
            .setTemperature(-0.2f)
            .setDownfall(0.8f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.FOREST)
            .setName("grove")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(29)
            .setBlockSearchExtent(8)
            .setReplaceCurrentMusic(false)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setMusicSound(BiomeSounds.OVERWORLD_GROVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8495359)
                    .build())
            .build();
    Biome SNOWY_SLOPES = new BiomeBuilder()
            .setTemperature(-0.3f)
            .setDownfall(0.9f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.MOUNTAIN)
            .setName("snowy_slopes")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(30)
            .setBlockSearchExtent(8)
            .setMusicSound(BiomeSounds.OVERWORLD_SNOWY_SLOPES)
            .setMusicMinimumDelay(12000)
            .setMusicMaximumDelay(24000)
            .setReplaceCurrentMusic(false)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8560639)
                    .build())
            .build();
    Biome FROZEN_PEAKS = new BiomeBuilder()
            .setTemperature(-0.7f)
            .setDownfall(0.9f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.MOUNTAIN)
            .setName("frozen_peaks")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setReplaceCurrentMusic(false)
            .setMusicSound(BiomeSounds.OVERWORLD_FROZEN_PEAKS)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setNetworkId(31)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8756735)
                    .build())
            .build();
    Biome JAGGED_PEAKS = new BiomeBuilder()
            .setTemperature(-0.7f)
            .setDownfall(0.9f)
            .setCategory(BiomeCategory.MOUNTAIN)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setName("jagged_peaks")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(32)
            .setMusicMinimumDelay(12000)
            .setMusicMaximumDelay(24000)
            .setMusicSound(BiomeSounds.OVERWORLD_JAGGED_PEAKS)
            .setReplaceCurrentMusic(false)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8756735)
                    .build())
            .build();
    Biome STONY_PEAKS = new BiomeBuilder()
            .setTemperature(1.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDownfall(0.3f)
            .setCategory(BiomeCategory.MOUNTAIN)
            .setName("stony_peaks")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(33)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setReplaceCurrentMusic(false)
            .setMusicSound(BiomeSounds.OVERWORLD_STONY_PEAKS)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7776511)
                    .build())
            .build();
    Biome RIVER = new BiomeBuilder()
            .setTemperature(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.RIVER)
            .setName("river")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(34)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome FROZEN_RIVER = new BiomeBuilder()
            .setTemperature(0.0f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.RIVER)
            .setName("frozen_river")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(35)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(3750089)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8364543)
                    .build())
            .build();
    Biome BEACH = new BiomeBuilder()
            .setTemperature(0.8f)
            .setDownfall(0.4f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.BEACH)
            .setName("beach")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(36)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7907327)
                    .build())
            .build();
    Biome SNOWY_BEACH = new BiomeBuilder()
            .setTemperature(0.05f)
            .setDownfall(0.3f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.BEACH)
            .setName("snowy_beach")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)

            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(37)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(4020182)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8364543)
                    .build())
            .build();
    Biome STONY_SHORE = new BiomeBuilder()
            .setTemperature(0.2f)
            .setDownfall(0.3f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.BEACH)
            .setName("stony_shore")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(38)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8233727)
                    .build())
            .build();
    Biome WARM_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.OCEAN)
            .setName("warm_ocean")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)

            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(39)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4445678)
                    .setFogColour(12638463)
                    .setWaterFogColour(270131)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome LUKEWARM_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.OCEAN)
            .setName("lukewarm_ocean")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(40)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4566514)
                    .setFogColour(12638463)
                    .setWaterFogColour(267827)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome DEEP_LUKEWARM_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.OCEAN)
            .setName("deep_lukewarm_ocean")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(41)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4566514)
                    .setFogColour(12638463)
                    .setWaterFogColour(267827)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.OCEAN)
            .setName("ocean")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)

            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(42)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome DEEP_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.OCEAN)
            .setName("deep_ocean")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(43)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome COLD_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.OCEAN)
            .setName("cold_ocean")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(44)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4020182)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome DEEP_COLD_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.OCEAN)
            .setName("deep_cold_ocean")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(45)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4020182)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome FROZEN_OCEAN = new BiomeBuilder()
            .setTemperature(0.0f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.OCEAN)
            .setName("frozen_ocean")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(46)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setTemperatureModifier(TemperatureModifier.FROZEN)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.SNOW)
                    .setWaterColour(3750089)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8364543)
                    .build())
            .build();
    Biome DEEP_FROZEN_OCEAN = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.OCEAN)
            .setTemperatureModifier(TemperatureModifier.FROZEN)
            .setName("deep_frozen_ocean")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setBlockSearchExtent(8)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(47)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(3750089)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome MUSHROOM_FIELDS = new BiomeBuilder()
            .setTemperature(0.9f)
            .setDownfall(1.0f)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.MUSHROOM)
            .setName("mushroom_fields")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(48)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7842047)
                    .build())
            .build();
    Biome DRIPSTONE_CAVES = new BiomeBuilder()
            .setTemperature(0.8f)
            .setDownfall(0.4f)
            .setCategory(BiomeCategory.UNDERGROUND)
            .setName("dripstone_caves")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(49)
            .setMusicMinimumDelay(12000)
            .setMusicMaximumDelay(24000)
            .setReplaceCurrentMusic(false)
            .setMusicSound(BiomeSounds.OVERWORLD_DRIPSTONE_CAVES)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(7907327)
                    .build())
            .build();
    Biome LUSH_CAVES = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.UNDERGROUND)
            .setName("lush_caves")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(50)
            .setReplaceCurrentMusic(false)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setBlockSearchExtent(8)
            .setMusicSound(BiomeSounds.OVERWORLD_LUSH_CAVES)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.RAIN)
                    .setWaterColour(4159204)
                    .setFogColour(12638463)
                    .setWaterFogColour(329011)
                    .setSkyColour(8103167)
                    .build())
            .build();
    Biome NETHER_WASTES = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setCategory(BiomeCategory.NETHER)
            .setName("nether_wastes")
            .setMoodSound(BiomeSounds.AMBIENT_NETHER_WASTES_MOOD)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setReplaceCurrentMusic(false)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setMusicSound(BiomeSounds.NETHER_WASTES)
            .setAmbientSound(BiomeSounds.NETHER_WASTES_LOOP)
            .setAdditionsSound(BiomeSounds.NETHER_WASTES_ADDITIONS)
            .setAdditionTickChance(0.0111)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(51)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(3344392)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();

    Biome WARPED_FOREST = new BiomeBuilder()
            .setTemperature(2.0f)
            .setMoodSound(BiomeSounds.AMBIENT_WARPED_FOREST_MOOD)
            .setAmbientSound(BiomeSounds.AMBIENT_WARPED_FOREST_LOOP)
            .setAdditionsSound(BiomeSounds.AMBIENT_WARPED_FOREST_ADDITIONS)
            .setMusicSound(BiomeSounds.NETHER_WARPED_FOREST)
            .setParticle(new ParticleBuilder()
                    .setProbability(0.01428f)
                    .setType(ParticleTypes.WARPED_SPORE)
                    .build())
            .setMusicMinimumDelay(12000)
            .setMusicMaximumDelay(24000)
            .setReplaceCurrentMusic(false)
            .setAdditionTickChance(0.0111)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDownfall(0.0f)
            .setCategory(BiomeCategory.NETHER)
            .setName("warped_forest")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(52)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(1705242)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();

    Biome CRIMSON_FOREST = new BiomeBuilder()
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWaterColour(4159204)
                    .setFogColour(3343107)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .setWeather(BiomeWeather.NONE)
                    .build())
            .setOffset(2.0)
            .setName("crimson_forest")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(53)
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setBlockSearchExtent(8)
            .setReplaceCurrentMusic(false)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setMoodSound(BiomeSounds.AMBIENT_CRIMSON_FOREST_MOOD)
            .setMusicSound(BiomeSounds.NETHER_CRIMSON_FOREST)
            .setAmbientSound(BiomeSounds.AMBIENT_CRIMSON_FOREST_LOOP)
            .setAdditionsSound(BiomeSounds.AMBIENT_CRIMSON_FOREST_ADDITIONS)
            .setAdditionTickChance(0.0111)
            .setParticle(new ParticleBuilder().setProbability(0.025f).setType(ParticleTypes.CRIMSON_SPORE).build())
            .setCategory(BiomeCategory.NETHER)
            .build();
    Biome SOUL_SAND_VALLEY = new BiomeBuilder()
            .setReplaceCurrentMusic(false)
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setMusicMaximumDelay(24000)
            .setMusicMinimumDelay(12000)
            .setMusicSound(BiomeSounds.SOUL_SAND_VALLEY)
            .setAdditionsSound(BiomeSounds.SOUL_SAND_VALLEY_ADDITIONS)
            .setAmbientSound(BiomeSounds.SOUL_SAND_VALLEY_LOOP)
            .setAdditionTickChance(0.0111)
            .setCategory(BiomeCategory.NETHER)
            .setParticle(new ParticleBuilder().setProbability(0.00625F).setType(ParticleTypes.ASH).build())
            .setName("soul_sand_valley")
            .setMoodSound(BiomeSounds.AMBIENT_SOAL_SAND_VALLEY_MOOD)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(54)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(1787717)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();
    Biome BASALT_DELTAS = new BiomeBuilder()
            .setTemperature(2.0f)
            .setDownfall(0.0f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.NETHER)
            .setAdditionTickChance(0.0111)
            .setMusicMinimumDelay(12000)
            .setMusicMaximumDelay(24000)
            .setParticle(new ParticleBuilder().setType(ParticleTypes.WHITE_ASH).setProbability(0.118093334F).build())
            .setAmbientSound(BiomeSounds.AMBIENT_BASALT_DELTAS_LOOP)
            .setAdditionsSound(BiomeSounds.AMBIENT_BASALT_DELTAS_ADDITIONS)
            .setMusicSound(BiomeSounds.BASALT_DELTAS)
            .setReplaceCurrentMusic(false)
            .setName("basalt_deltas")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setMoodSound(BiomeSounds.AMBIENT_BASALT_DELTAS_MOOD)
            .setNetworkId(55)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(6840176)
                    .setWaterFogColour(329011)
                    .setSkyColour(7254527)
                    .build())
            .build();
    Biome THE_END = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.THE_END)
            .setName("the_end")
            .setBlockSearchExtent(8)

            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(56)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(10518688)
                    .setWaterFogColour(329011)
                    .setSkyColour(0)
                    .build())
            .build();
    Biome END_HIGHLANDS = new BiomeBuilder()
            .setTemperature(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.THE_END)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setName("end_highlands")
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(57)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(10518688)
                    .setWaterFogColour(329011)
                    .setSkyColour(0)
                    .build())
            .build();
    Biome END_MIDLANDS = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setCategory(BiomeCategory.THE_END)
            .setName("end_midlands")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(58)
            .setBlockSearchExtent(8)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(10518688)
                    .setWaterFogColour(329011)
                    .setSkyColour(0)
                    .build())
            .build();
    Biome SMALL_END_ISLANDS = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.THE_END)
            .setName("small_end_islands")
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(59)
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)

            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(10518688)
                    .setWaterFogColour(329011)
                    .setSkyColour(0)
                    .build())
            .build();
    Biome END_BARRENS = new BiomeBuilder()
            .setTemperature(0.5f)
            .setDownfall(0.5f)
            .setCategory(BiomeCategory.THE_END)
            .setName("end_barrens")
            .setTickDelay(6000)
            .setOffset(2.0)
            .setBlockSearchExtent(8)
            .setMoodSound(BiomeSounds.AMBIENT_CAVE)
            .setHost(Identifiable.MINECRAFT_HOST)
            .setNetworkId(60)
            .setDefaultProperties(new BiomePropertiesBuilder()
                    .setWeather(BiomeWeather.NONE)
                    .setWaterColour(4159204)
                    .setFogColour(10518688)
                    .setWaterFogColour(329011)
                    .setSkyColour(0)
                    .build())
            .build();

}
